schema_version: 1

context:
  name: amazon-textract-response-parser
  version: 1.0.3
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7d7f56702bb576e24949ff5ca98d75d546fec12923ee97e399f6b72f5c6db018

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - boto3
    - python >=${{ python_min }}
    - marshmallow >=3.14,<4

tests:
  - python:
      imports:
        - a2i
        - trp
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Easily parse JSON returned by Amazon Textract.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/aws-samples/amazon-textract-response-parser

extra:
  recipe-maintainers:
    - StevenSchaererQC
